version: "3.8"

services:
  wsi_service:
    build:
      dockerfile: "build_standalone/Dockerfile"
      context: "."
      target: wsi_service_production
      network: "${COMPOSE_NETWORK}"
    restart: "${COMPOSE_RESTART}"
    environment:
      - WS_CORS_ALLOW_CREDENTIALS=${WS_CORS_ALLOW_CREDENTIALS}
      - WS_CORS_ALLOW_ORIGINS=${WS_CORS_ALLOW_ORIGINS}
      - WS_DEBUG=${WS_DEBUG}
      - WS_DISABLE_OPENAPI=${WS_DISABLE_OPENAPI}
      - WS_MAPPER_ADDRESS=${WS_MAPPER_ADDRESS}
      - WS_LOCAL_MODE=${WS_LOCAL_MODE}
      - WS_ENABLE_VIEWER_ROUTES=${WS_ENABLE_VIEWER_ROUTES}
      - WS_INACTIVE_HISTO_IMAGE_TIMEOUT_SECONDS=${WS_INACTIVE_HISTO_IMAGE_TIMEOUT_SECONDS}
      - WS_MAX_RETURNED_REGION_SIZE=${WS_MAX_RETURNED_REGION_SIZE}
      # Auth
      - WS_API_V3_INTEGRATION=${WS_API_V3_INTEGRATION}
      - WS_IDP_URL=${WS_IDP_URL}
      - WS_CLIENT_ID=${WS_CLIENT_ID}
      - WS_ORGANIZATION_ID=${WS_ORGANIZATION_ID}
      - WS_CLIENT_SECRET=${WS_CLIENT_SECRET}
      - WS_AUDIENCE=${WS_AUDIENCE}
      - WS_OPENAPI_AUTH_URL=${WS_OPENAPI_AUTH_URL}
      - WS_OPENAPI_TOKEN_URL=${WS_OPENAPI_TOKEN_URL}
      - WS_REWRITE_URL_IN_WELLKNOWN=${WS_REWRITE_URL_IN_WELLKNOWN}
      - WS_REFRESH_INTERVAL=${WS_REFRESH_INTERVAL}
    volumes:
      - ${COMPOSE_DATA_DIR}:/data
    ports:
      - ${COMPOSE_WS_PORT}:8080
